export type QuestionCategory =
  | "Us"
  | "Deep"
  | "Memory Lane"
  | "Dream Big"
  | "Hot Takes"
  | "Hypothetical"
  | "Intimacy"
  | "Gratitude"
  | "Play"
  | "Before Us";

export interface DailyQuestion {
  text: string;
  category: QuestionCategory;
}

const QUESTIONS: DailyQuestion[] = [
  // ── Us ──
  { text: "What's one thing I do that instantly makes your day better?", category: "Us" },
  { text: "When did you first realize this was more than a crush?", category: "Us" },
  { text: "What do you think is the thing that keeps us together?", category: "Us" },
  { text: "What's a habit of mine you secretly find adorable?", category: "Us" },
  { text: "If our relationship had a movie title, what would it be?", category: "Us" },
  { text: "What's something we do better as a team than anyone else?", category: "Us" },
  { text: "What's one thing about us you'd never want to change?", category: "Us" },
  { text: "How would you describe our relationship to a stranger in one sentence?", category: "Us" },
  { text: "What's a fight we had that actually made us stronger?", category: "Us" },
  { text: "What unspoken rule do we have that nobody else would understand?", category: "Us" },
  { text: "If you had to pick one word to describe our energy together, what is it?", category: "Us" },
  { text: "What's the weirdest thing that only makes sense between us?", category: "Us" },
  { text: "What do you think people notice first about us as a couple?", category: "Us" },
  { text: "What's your favorite way we say 'I love you' without saying it?", category: "Us" },
  { text: "What's a challenge we haven't faced yet that you're nervous about?", category: "Us" },
  { text: "When do you feel most like a team with me?", category: "Us" },
  { text: "What's the most 'us' thing we could possibly do on a random Tuesday?", category: "Us" },
  { text: "If we had a couples superpower, what would it be?", category: "Us" },
  { text: "What's one thing you still wonder about me but have never asked?", category: "Us" },
  { text: "What's the best piece of advice you'd give to a new couple based on us?", category: "Us" },
  { text: "What's a small tradition we have that means more than it seems?", category: "Us" },
  { text: "What song plays in your head when you think of us?", category: "Us" },
  { text: "What's the bravest thing you've ever done for this relationship?", category: "Us" },
  { text: "What do you think our biggest growth area is right now?", category: "Us" },
  { text: "How has loving me changed the way you see yourself?", category: "Us" },
  { text: "What part of our daily routine is secretly sacred to you?", category: "Us" },
  { text: "What's one thing about us that you're quietly proud of?", category: "Us" },
  { text: "If you could freeze one moment of us in time forever, which one?", category: "Us" },
  { text: "What's the funniest misunderstanding we've ever had?", category: "Us" },
  { text: "What do you think I understand about you better than anyone?", category: "Us" },

  // ── Deep ──
  { text: "What's a belief you hold that most people in your life would disagree with?", category: "Deep" },
  { text: "What's the hardest truth you've had to accept about yourself?", category: "Deep" },
  { text: "If you could know the absolute truth to one question, what would you ask?", category: "Deep" },
  { text: "What does 'home' mean to you — not a place, a feeling?", category: "Deep" },
  { text: "What are you most afraid of losing?", category: "Deep" },
  { text: "Do you think people can truly change, or just learn to manage who they are?", category: "Deep" },
  { text: "What's something you pretend doesn't bother you but actually does?", category: "Deep" },
  { text: "What would you do differently if nobody was watching or judging?", category: "Deep" },
  { text: "What's the wisest thing anyone has ever said to you?", category: "Deep" },
  { text: "Do you think we choose who we love, or does it choose us?", category: "Deep" },
  { text: "What part of your personality do you wish more people saw?", category: "Deep" },
  { text: "What's something you've forgiven but never forgotten?", category: "Deep" },
  { text: "If your younger self could see your life now, what would surprise them most?", category: "Deep" },
  { text: "What does success actually look like to you — not what society says?", category: "Deep" },
  { text: "What do you think happens when we die?", category: "Deep" },
  { text: "What's a value you'll never compromise on, no matter what?", category: "Deep" },
  { text: "What keeps you up at 3am?", category: "Deep" },
  { text: "What lesson did life teach you in the worst possible way?", category: "Deep" },
  { text: "Do you think happiness is a choice or a circumstance?", category: "Deep" },
  { text: "What's the most important conversation you've never had?", category: "Deep" },
  { text: "What are you running from? What are you running toward?", category: "Deep" },
  { text: "What does vulnerability feel like in your body?", category: "Deep" },
  { text: "What would you want written on your headstone?", category: "Deep" },
  { text: "What's one thing you're still trying to prove to yourself?", category: "Deep" },
  { text: "If you had to give a TED talk tomorrow, what would it be about?", category: "Deep" },
  { text: "What's the most courageous thing you've ever done quietly?", category: "Deep" },
  { text: "What emotion do you have the hardest time sitting with?", category: "Deep" },
  { text: "What's a question you're afraid to know the answer to?", category: "Deep" },
  { text: "What do you think your purpose is — or are you still figuring it out?", category: "Deep" },
  { text: "What's one thing about the world that breaks your heart?", category: "Deep" },

  // ── Memory Lane ──
  { text: "What's the first thing you remember thinking when we met?", category: "Memory Lane" },
  { text: "What's a random moment together that you think about more than you should?", category: "Memory Lane" },
  { text: "What's the best date we've ever been on?", category: "Memory Lane" },
  { text: "What's a moment where you fell in love with me all over again?", category: "Memory Lane" },
  { text: "What's the hardest laugh we've ever shared?", category: "Memory Lane" },
  { text: "What's a trip or adventure we took that changed something between us?", category: "Memory Lane" },
  { text: "What's a gift I gave you that meant more than I probably realized?", category: "Memory Lane" },
  { text: "What's a moment you were scared but didn't show it?", category: "Memory Lane" },
  { text: "What's a photo of us you wish existed but we never took?", category: "Memory Lane" },
  { text: "What was the most stressful thing we went through, and how did it end?", category: "Memory Lane" },
  { text: "What's an inside joke between us that still makes you smile?", category: "Memory Lane" },
  { text: "What's the most spontaneous thing we've ever done?", category: "Memory Lane" },
  { text: "What's a meal we shared that you'll never forget?", category: "Memory Lane" },
  { text: "When was the last time I surprised you in a good way?", category: "Memory Lane" },
  { text: "What's a conversation we had that completely shifted your perspective?", category: "Memory Lane" },
  { text: "What's your favorite 'normal' memory of us — not a big event, just ordinary life?", category: "Memory Lane" },
  { text: "What's a time you were really proud of me but maybe never said so?", category: "Memory Lane" },
  { text: "What's the most romantic thing that's happened between us naturally?", category: "Memory Lane" },
  { text: "What place holds the most memories for us?", category: "Memory Lane" },
  { text: "What's a time I made you feel completely safe?", category: "Memory Lane" },
  { text: "What's a mistake one of us made that became a funny story?", category: "Memory Lane" },
  { text: "What moment together felt like a scene from a movie?", category: "Memory Lane" },
  { text: "What's the most surprising thing you've learned about me over time?", category: "Memory Lane" },
  { text: "What's a small kindness from me that you've never forgotten?", category: "Memory Lane" },
  { text: "What was the turning point when 'dating' became 'this is it'?", category: "Memory Lane" },

  // ── Dream Big ──
  { text: "If money and time were no object, what would our life look like in 10 years?", category: "Dream Big" },
  { text: "What's one wild dream you haven't told anyone about?", category: "Dream Big" },
  { text: "Where in the world would you build our dream home?", category: "Dream Big" },
  { text: "What's a skill you'd love both of us to learn together?", category: "Dream Big" },
  { text: "If we could start a business together, what would it be?", category: "Dream Big" },
  { text: "What's on your bucket list that you haven't crossed off yet?", category: "Dream Big" },
  { text: "What kind of old couple do you want us to be?", category: "Dream Big" },
  { text: "If we could take a year off and go anywhere, what's the itinerary?", category: "Dream Big" },
  { text: "What's a project you'd love us to build or create together?", category: "Dream Big" },
  { text: "If you could master anything overnight, what would it be?", category: "Dream Big" },
  { text: "What's a tradition you want us to start this year?", category: "Dream Big" },
  { text: "What does your ideal regular day look like in 5 years?", category: "Dream Big" },
  { text: "What's one thing you want to accomplish before you turn 50?", category: "Dream Big" },
  { text: "If we could live abroad for a year, where would we go?", category: "Dream Big" },
  { text: "What's a fear you want to face together?", category: "Dream Big" },
  { text: "What's the craziest goal you'd pursue if failure wasn't an option?", category: "Dream Big" },
  { text: "How do you want people to describe our life when we're 80?", category: "Dream Big" },
  { text: "What's a cause or mission you want to dedicate more time to?", category: "Dream Big" },
  { text: "What experience do you want to have at least once in your life?", category: "Dream Big" },
  { text: "If we wrote a book together, what would it be about?", category: "Dream Big" },
  { text: "What does 'legacy' mean to you?", category: "Dream Big" },
  { text: "What's the next adventure you want us to take?", category: "Dream Big" },
  { text: "If you could redesign our daily routine from scratch, what changes?", category: "Dream Big" },
  { text: "What's a promise you want us to make to each other right now?", category: "Dream Big" },
  { text: "What's the most important thing we should be investing in — time, money, or energy?", category: "Dream Big" },

  // ── Hot Takes ──
  { text: "What's a popular opinion that you think is completely wrong?", category: "Hot Takes" },
  { text: "What's the most overrated thing in modern dating culture?", category: "Hot Takes" },
  { text: "Do you think social media helps or hurts relationships?", category: "Hot Takes" },
  { text: "Is it ever okay to lie to protect someone's feelings?", category: "Hot Takes" },
  { text: "What's a 'red flag' that you actually think is fine?", category: "Hot Takes" },
  { text: "What's the most overrated restaurant, movie, or trend right now?", category: "Hot Takes" },
  { text: "Do you think couples should share passwords?", category: "Hot Takes" },
  { text: "Is being 'too comfortable' in a relationship a real thing?", category: "Hot Takes" },
  { text: "What's a take you have about love that would start a debate?", category: "Hot Takes" },
  { text: "Do you think people should stay friends with their exes?", category: "Hot Takes" },
  { text: "What's the worst relationship advice people give?", category: "Hot Takes" },
  { text: "Is jealousy always bad, or can it be healthy sometimes?", category: "Hot Takes" },
  { text: "What's something society romanticizes that's actually toxic?", category: "Hot Takes" },
  { text: "Do you think love languages are real or just a trend?", category: "Hot Takes" },
  { text: "What's a hill you'd die on that nobody else cares about?", category: "Hot Takes" },
  { text: "Should couples always go to bed at the same time?", category: "Hot Takes" },
  { text: "What's the most overhyped life milestone?", category: "Hot Takes" },
  { text: "Is 'the one' real, or do you just choose someone and build?", category: "Hot Takes" },
  { text: "What's an unpopular food opinion you stand by?", category: "Hot Takes" },
  { text: "Do you think people fall out of love, or just stop choosing each other?", category: "Hot Takes" },
  { text: "What's a movie or show everyone loves that you can't stand?", category: "Hot Takes" },
  { text: "Is it better to be brutally honest or gently kind?", category: "Hot Takes" },
  { text: "What generation had it figured out the most?", category: "Hot Takes" },
  { text: "Is it possible to love two people at once?", category: "Hot Takes" },
  { text: "What's the biggest myth about long-term relationships?", category: "Hot Takes" },

  // ── Hypothetical ──
  { text: "If you could wake up tomorrow with one new ability, what would it be?", category: "Hypothetical" },
  { text: "If we had to survive a zombie apocalypse together, what's our game plan?", category: "Hypothetical" },
  { text: "If you could live in any fictional universe, which one and why?", category: "Hypothetical" },
  { text: "Would you rather always know what people are thinking or always know the future?", category: "Hypothetical" },
  { text: "If we had to pick a different era to live in, when would you choose?", category: "Hypothetical" },
  { text: "If you could have dinner with anyone — alive or dead — who would it be?", category: "Hypothetical" },
  { text: "Would you rather be famous and lonely or unknown and deeply loved?", category: "Hypothetical" },
  { text: "If you could swap lives with me for 24 hours, what's the first thing you'd do?", category: "Hypothetical" },
  { text: "If we found a suitcase with $1 million cash, what do we do?", category: "Hypothetical" },
  { text: "Would you rather never age physically or never age mentally?", category: "Hypothetical" },
  { text: "If you could only eat one cuisine for the rest of your life, what is it?", category: "Hypothetical" },
  { text: "If aliens landed and asked you to explain love, what would you say?", category: "Hypothetical" },
  { text: "Would you rather have more time or more money?", category: "Hypothetical" },
  { text: "If you could uninvent one thing, what would it be?", category: "Hypothetical" },
  { text: "If we were characters in a video game, what genre would it be?", category: "Hypothetical" },
  { text: "Would you rather live in a cabin in the mountains or a beach house by the ocean?", category: "Hypothetical" },
  { text: "If you could relive any year of your life, which would it be?", category: "Hypothetical" },
  { text: "If we discovered a portal to a parallel universe, would you go through it?", category: "Hypothetical" },
  { text: "Would you rather always be overdressed or always be underdressed?", category: "Hypothetical" },
  { text: "If you could make one rule everyone in the world had to follow, what would it be?", category: "Hypothetical" },
  { text: "Would you rather live without music or live without movies?", category: "Hypothetical" },
  { text: "If you could redo one decision in your life, would you? Which one?", category: "Hypothetical" },
  { text: "If we could teleport anywhere right now for one hour, where do we go?", category: "Hypothetical" },
  { text: "Would you rather always say everything on your mind or never speak again?", category: "Hypothetical" },
  { text: "If time froze for everyone except you for one day, what would you do?", category: "Hypothetical" },

  // ── Intimacy ──
  { text: "What's one thing I could do to make you feel more loved this week?", category: "Intimacy" },
  { text: "When do you feel closest to me?", category: "Intimacy" },
  { text: "What's something vulnerable you've been wanting to share but haven't?", category: "Intimacy" },
  { text: "How do you most like to be comforted when you're upset?", category: "Intimacy" },
  { text: "What does feeling safe in our relationship mean to you?", category: "Intimacy" },
  { text: "What's your love language when you're stressed vs. when you're happy?", category: "Intimacy" },
  { text: "What's a way I show love that maybe I don't even realize?", category: "Intimacy" },
  { text: "When was the last time you felt truly seen by me?", category: "Intimacy" },
  { text: "What's one thing you need from me that you've been too shy to ask for?", category: "Intimacy" },
  { text: "What does trust look like to you in a relationship?", category: "Intimacy" },
  { text: "What's the most attractive thing about me that isn't physical?", category: "Intimacy" },
  { text: "What's a moment recently where you wished I was there?", category: "Intimacy" },
  { text: "How do you know when I'm having a bad day without me saying anything?", category: "Intimacy" },
  { text: "What's the hardest thing about being emotionally open with me?", category: "Intimacy" },
  { text: "What does intimacy mean to you beyond the physical?", category: "Intimacy" },
  { text: "What's a part of yourself you're still learning to love?", category: "Intimacy" },
  { text: "When do you feel most beautiful or confident?", category: "Intimacy" },
  { text: "What's something I said once that you've carried with you ever since?", category: "Intimacy" },
  { text: "What do you wish you could tell me without worrying how I'd react?", category: "Intimacy" },
  { text: "How can I be a better listener for you?", category: "Intimacy" },
  { text: "What scares you most about being fully known by someone?", category: "Intimacy" },
  { text: "What's the most tender moment we've shared?", category: "Intimacy" },
  { text: "When do you feel the most 'you' around me?", category: "Intimacy" },
  { text: "What's a boundary of yours that you're grateful I respect?", category: "Intimacy" },
  { text: "What do you need more of in our relationship right now?", category: "Intimacy" },

  // ── Gratitude ──
  { text: "What's something I did recently that made you feel appreciated?", category: "Gratitude" },
  { text: "What's one thing about your life right now that you'd never trade?", category: "Gratitude" },
  { text: "What's a quality in me that you're most grateful for?", category: "Gratitude" },
  { text: "What's the best thing that happened to you this week?", category: "Gratitude" },
  { text: "Who outside of us has had the biggest positive impact on your life?", category: "Gratitude" },
  { text: "What's a 'boring' part of our routine that you secretly love?", category: "Gratitude" },
  { text: "What's one thing about today that you want to remember?", category: "Gratitude" },
  { text: "What's a lesson from a hard time that you're now grateful for?", category: "Gratitude" },
  { text: "What's the most underrated thing about our life together?", category: "Gratitude" },
  { text: "What's a simple pleasure that always makes your day?", category: "Gratitude" },
  { text: "What's something about your body or health that you're grateful for?", category: "Gratitude" },
  { text: "When was the last time you felt genuinely lucky?", category: "Gratitude" },
  { text: "What's a struggle that taught you something you needed to learn?", category: "Gratitude" },
  { text: "What's one way I've made your life easier that I probably don't know about?", category: "Gratitude" },
  { text: "What are three small things you're grateful for right now?", category: "Gratitude" },
  { text: "What's a friendship you're really thankful for and why?", category: "Gratitude" },
  { text: "What's something about this season of life that you want to savor?", category: "Gratitude" },
  { text: "What's a comfort you have now that you once only dreamed about?", category: "Gratitude" },
  { text: "What about me surprised you in the best way?", category: "Gratitude" },
  { text: "If you wrote a thank-you letter to the universe, what would it say?", category: "Gratitude" },
  { text: "What's one way our relationship has made you a better person?", category: "Gratitude" },
  { text: "What's the kindest thing a stranger has ever done for you?", category: "Gratitude" },
  { text: "What's something you used to take for granted but don't anymore?", category: "Gratitude" },
  { text: "What's the best risk you've ever taken?", category: "Gratitude" },
  { text: "What's one thing about our home that makes you feel at peace?", category: "Gratitude" },

  // ── Play ──
  { text: "What's the most embarrassing song on your playlist right now?", category: "Play" },
  { text: "If you were a sandwich, what kind of sandwich would you be?", category: "Play" },
  { text: "What's the worst fashion choice you've ever made?", category: "Play" },
  { text: "If our pets could talk, what would they say about us?", category: "Play" },
  { text: "What's the dumbest thing you've ever Googled?", category: "Play" },
  { text: "If you had to eat one meal for every meal for a week, what is it?", category: "Play" },
  { text: "What's your guilty pleasure TV show or movie?", category: "Play" },
  { text: "If you could only use one emoji for the rest of your life, which one?", category: "Play" },
  { text: "What's the most useless talent you have?", category: "Play" },
  { text: "If you were a character in a sitcom, which show would it be?", category: "Play" },
  { text: "What's your go-to karaoke song, no hesitation?", category: "Play" },
  { text: "What nickname would you secretly love me to call you?", category: "Play" },
  { text: "If we had a couples Halloween costume, what would it be?", category: "Play" },
  { text: "What's the weirdest food combo you genuinely enjoy?", category: "Play" },
  { text: "If you could be any age forever, what age and why?", category: "Play" },
  { text: "What's the most chaotic thing you've done while home alone?", category: "Play" },
  { text: "If we started a band, what would we be called?", category: "Play" },
  { text: "What celebrity do people say you look like (and do you agree)?", category: "Play" },
  { text: "What's your most controversial food take?", category: "Play" },
  { text: "If we had to compete on a reality show, which one would we dominate?", category: "Play" },
  { text: "What's the worst date idea you can think of?", category: "Play" },
  { text: "What would your rapper name be?", category: "Play" },
  { text: "If you could make one weird law, what would it be?", category: "Play" },
  { text: "What's the pettiest argument we've ever had?", category: "Play" },
  { text: "If our relationship had a Yelp review, what would it say?", category: "Play" },

  // ── Before Us ──
  { text: "What were you like as a kid? Describe yourself in three words.", category: "Before Us" },
  { text: "What's a childhood memory that you think about a lot?", category: "Before Us" },
  { text: "What was your family's dinner table like growing up?", category: "Before Us" },
  { text: "Who was your first crush and what were they like?", category: "Before Us" },
  { text: "What's a phase you went through that you'd love to forget?", category: "Before Us" },
  { text: "What's the best thing your parents taught you about love?", category: "Before Us" },
  { text: "What's a dream you had as a kid that you've let go of?", category: "Before Us" },
  { text: "What was the hardest year of your life before we met?", category: "Before Us" },
  { text: "What's a school memory — good or bad — that shaped you?", category: "Before Us" },
  { text: "Who was the most influential person in your childhood?", category: "Before Us" },
  { text: "What did you want to be when you grew up?", category: "Before Us" },
  { text: "What's a song that takes you straight back to your teenage years?", category: "Before Us" },
  { text: "What's the biggest lesson a past relationship taught you?", category: "Before Us" },
  { text: "What's a place from your childhood that you'd love to visit again?", category: "Before Us" },
  { text: "What were you most insecure about as a teenager?", category: "Before Us" },
  { text: "What's a tradition from your family that you want to keep alive?", category: "Before Us" },
  { text: "What was the first job you ever had?", category: "Before Us" },
  { text: "What's something about your hometown that you miss?", category: "Before Us" },
  { text: "What's the best birthday you ever had growing up?", category: "Before Us" },
  { text: "Who was your childhood best friend and where are they now?", category: "Before Us" },
  { text: "What was the first album or artist you were obsessed with?", category: "Before Us" },
  { text: "What's a rule your parents had that you thought was unfair?", category: "Before Us" },
  { text: "What was your biggest fear as a kid?", category: "Before Us" },
  { text: "What's a moment from before we met that you wish I could've seen?", category: "Before Us" },
  { text: "If you could go back and tell your 16-year-old self one thing, what would it be?", category: "Before Us" },
];

function hashDate(dateStr: string): number {
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    const char = dateStr.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return Math.abs(hash);
}

export function getDailyQuestion(dateStr: string): DailyQuestion {
  const index = hashDate(dateStr + "q") % QUESTIONS.length;
  return QUESTIONS[index];
}
