const PROMPTS: string[] = [
  "What's something your partner does that always makes you smile?",
  "What's a word you recently learned the meaning of?",
  "What's something you saw today that surprised you?",
  "What's a small habit of yours that most people don't know about?",
  "What's a place you'd love to visit together someday?",
  "What's a song that reminds you of your partner?",
  "What's something you learned from a stranger?",
  "What's a childhood memory that shaped who you are?",
  "What's the most interesting thing you read this week?",
  "What's a skill you wish you had?",
  "What's a food you've never tried but want to?",
  "What's something beautiful you noticed today?",
  "What's a movie scene that stuck with you?",
  "What's a dream you haven't told anyone about?",
  "What's the best advice you've ever received?",
  "What's something you're proud of but rarely talk about?",
  "What's a question you've always wanted to ask your partner?",
  "What's a random fact that blew your mind?",
  "What's your earliest memory?",
  "What's a tradition you'd love to start together?",
  "What made you laugh today?",
  "What's something that scared you as a child but doesn't anymore?",
  "What's a book that changed how you think?",
  "What's the most thoughtful gift you've ever received?",
  "What's something you find endlessly fascinating?",
  "What's a moment when you felt truly at peace?",
  "What's your favorite sound?",
  "What's a lesson you learned the hard way?",
  "What's something about the world that confuses you?",
  "What's a compliment you'll never forget?",
  "What's a smell that brings back a specific memory?",
  "What's something you used to believe but don't anymore?",
  "What's the most interesting conversation you've had recently?",
  "What's a talent your partner has that you admire?",
  "What's the kindest thing someone did for you this year?",
  "What's an unpopular opinion you hold?",
  "What's a historical event you wish you could have witnessed?",
  "What's something that always cheers you up?",
  "What's a word in another language you love?",
  "What's the strangest dream you've ever had?",
  "What's something you want to learn together?",
  "What's the best meal you've ever had?",
  "What's an invention you think the world still needs?",
  "What's a quality in your partner you hope to develop in yourself?",
  "What's something you discovered about yourself recently?",
  "What's the most beautiful place you've ever been?",
  "What's a habit you're trying to build?",
  "What's your favorite time of day and why?",
  "What's a piece of art that moved you?",
  "What's something that made you curious today?",
  "What's the most interesting animal fact you know?",
  "What's a moment from your relationship you'd relive?",
  "What's something you're grateful for right now?",
  "What's a conspiracy theory you find entertaining?",
  "What's the best piece of writing you've ever read?",
  "What's something you'd put in a time capsule?",
  "What's a fear you've overcome?",
  "What's your favorite thing about rainy days?",
  "What's something about your partner that you noticed recently?",
  "What's a scientific discovery that amazes you?",
  "What's a rule you live by?",
  "What's the most spontaneous thing you've ever done?",
  "What's something you wish more people knew about?",
  "What's a texture you find satisfying?",
  "What's a story from your family history?",
  "What's the most useful thing you learned in school?",
  "What's a color that makes you feel calm?",
  "What's something you'd love to teach your future kids?",
  "What's the best sunrise or sunset you've seen?",
  "What's something you changed your mind about?",
  "What's a museum you'd love to visit?",
  "What's a hobby you've always wanted to try?",
  "What's the funniest thing that happened to you?",
  "What's an act of kindness you witnessed?",
  "What's something your partner said that stuck with you?",
  "What's a mystery you'd love to solve?",
  "What's the most interesting documentary you've watched?",
  "What's something about nature that amazes you?",
  "What's a quote that resonates with you?",
  "What's a skill your partner has that surprises people?",
  "What's an experience that changed your perspective?",
  "What's the most interesting thing about your hometown?",
  "What's a language you'd love to learn?",
  "What's something that made you feel brave?",
  "What's the best photo you've ever taken?",
  "What's a topic you could talk about for hours?",
  "What's something you always carry with you?",
  "What's the most interesting building you've seen?",
  "What's something you'd do differently if you could?",
  "What's a flavor combination you love?",
  "What's the most meaningful tradition in your family?",
  "What's something you find oddly satisfying?",
  "What's a podcast episode that made you think?",
  "What's a superpower you'd want for a day?",
  "What's the most creative thing you've ever made?",
  "What's something about space that fascinates you?",
  "What's a cultural practice you find beautiful?",
  "What's the bravest thing your partner has done?",
  "What's something you want to be remembered for?",
  "What's a game you loved as a child?",
  "What's the most unexpected thing you've learned about your partner?",
  "What's a boundary you're proud of setting?",
  "What's something you find romantic that others might not?",
  "What's the best concert or show you've attended?",
  "What's a word that describes how you're feeling right now?",
  "What's something you believe in that you can't prove?",
  "What's a season you feel most alive in?",
  "What's the most thoughtful thing your partner does regularly?",
  "What's an old technology you miss?",
  "What's something that always makes you nostalgic?",
  "What's a project you'd love to work on together?",
  "What's the best decision you've ever made?",
  "What's something you wish you could see for the first time again?",
  "What's a ritual you do every morning?",
  "What's the most interesting job you've heard of?",
  "What's something you've been overthinking?",
  "What's a place that feels like home (other than home)?",
  "What's the most interesting thing about the ocean?",
  "What's something you want your partner to know?",
  "What's a challenge you're currently facing?",
  "What's a TV show that shaped your sense of humor?",
  "What's the most interesting street you've walked down?",
  "What's something you'd love to see in person?",
  "What's a dish you'd love to master cooking?",
  "What's the weirdest thing you find attractive?",
  "What's a cause you care deeply about?",
  "What's something you've been meaning to tell your partner?",
  "What's the most interesting piece of architecture near you?",
  "What's a habit of your partner's you've adopted?",
  "What's something you want to do before the year ends?",
  "What's a myth you believed way too long?",
  "What's the most important thing in a friendship?",
  "What's a texture in nature you love touching?",
  "What's something about the future that excites you?",
  "What's the best compliment you could give your partner?",
  "What's a small luxury you enjoy?",
  "What's something you always notice that others don't?",
  "What's a festival or holiday you'd love to experience?",
  "What's the most interesting fact about the human body?",
  "What's a type of weather you secretly enjoy?",
  "What's something your partner does that makes you feel safe?",
  "What's an era you'd love to time-travel to?",
  "What's the most bizarre food you've eaten?",
  "What's something you pretend to understand but don't?",
  "What's your favorite way to spend a Sunday?",
  "What's a philosophical question that keeps you up?",
  "What's the most magical place you've been?",
  "What's something you'd love to photograph?",
  "What's a sound that instantly relaxes you?",
  "What's the most interesting Wikipedia rabbit hole you've gone down?",
  "What's something you associate with your partner?",
  "What's a skill you think everyone should learn?",
  "What's the most interesting thing about your name?",
  "What's a tiny detail you love about your home?",
  "What's something that went better than expected?",
  "What's a flavor that takes you back to childhood?",
  "What's the most thoughtful gesture you've witnessed?",
  "What's something you'd love to collect?",
  "What's a scientific concept you find beautiful?",
  "What's the most interesting conversation starter you know?",
  "What's something you want to explore in your city?",
  "What's a moment when time seemed to stop?",
  "What's the best thing about being alive right now?",
  "What's something unusual you find beautiful?",
  "What's a tradition from another culture you admire?",
  "What's the most interesting cloud formation you've seen?",
  "What's something you learned from your partner?",
  "What's a feeling you wish you could bottle up?",
  "What's the most interesting thing about trees?",
  "What's a comfort food that fixes everything?",
  "What's something you'd love to witness in nature?",
  "What's an everyday object you think is beautifully designed?",
  "What's a story you love telling?",
  "What's the most interesting use of math in real life?",
  "What's something about your partner's past that fascinates you?",
  "What's a piece of clothing that has a story behind it?",
  "What's the most interesting thing about sleep?",
  "What's a goal you and your partner share?",
  "What's something that exists today that would amaze people 100 years ago?",
  "What's the most interesting pattern in nature?",
  "What's your definition of adventure?",
  "What's something you'd love to witness from history?",
  "What's a meal that tells a story?",
  "What's the most fascinating thing about language?",
  "What's something you want to build or create?",
  "What's a view you'd never get tired of?",
  "What's the most interesting thing about your birth month?",
  "What's something that connects you and your partner deeply?",
  "What's a daily ritual you cherish?",
  "What's the most interesting thing about the night sky?",
  "What's something you'd put on a billboard?",
  "What's a moment of pure joy you remember?",
  "What's the most interesting adaptation in nature?",
  "What's something you wish was taught in school?",
  "What's a way your partner makes ordinary moments special?",
  "What's the most interesting thing about water?",
  "What's a personal record you'd love to break?",
  "What's something about gravity you find mind-bending?",
  "What's a local spot you'd love to show your partner?",
  "What's the most interesting coincidence you've experienced?",
  "What's a feeling you get that you can't quite name?",
  "What's the most beautiful piece of music you've heard?",
  "What's something you'd love to learn about your partner's childhood?",
  "What's the most interesting thing about fire?",
  "What's a way you've grown in the past year?",
  "What's something you think about when you can't sleep?",
  "What's the most interesting map you've seen?",
  "What's a tiny moment with your partner you treasure?",
  "What's the most interesting thing about time?",
  "What's something you'd love to see from a bird's-eye view?",
  "What's a lesson nature teaches us?",
  "What's the most interesting use of color you've seen?",
  "What's a daily discovery you made this week?",
  "What's something about your relationship that surprised you?",
  "What's the most interesting thing about the moon?",
  "What's a place you feel creative?",
  "What's something mundane that you find profound?",
  "What's the most interesting symmetry in nature?",
  "What's a moment when you felt truly understood?",
  "What's something about light that fascinates you?",
  "What's a small change that improved your life?",
  "What's the most interesting thing about music?",
  "What's something you want to try this month?",
  "What's a way your partner surprised you recently?",
  "What's the most interesting thing about soil or earth?",
  "What's a new perspective you gained recently?",
  "What's something old that's still better than the modern version?",
  "What's the most interesting number you know a fact about?",
  "What's something in your daily routine you'd miss if it changed?",
  "What's the most fascinating migration pattern you've heard of?",
  "What's a feeling your partner gives you that no one else does?",
  "What's the most interesting thing about silence?",
  "What's a question you'd ask the universe?",
  "What's the most interesting thing about mirrors?",
  "What's something you find poetic in everyday life?",
  "What's a challenge that made you stronger?",
  "What's the most interesting thing about rainbows?",
  "What's something you noticed about the world today?",
  "What's a wish you have for your partner?",
  "What's the most interesting thing about shadows?",
  "What's something you'd love to write about?",
  "What's a simple pleasure you never take for granted?",
  "What's something your partner taught you without realizing it?",
  "What's the most interesting thing about echoes?",
  "What's a moment when everything felt right?",
  "What's the most interesting thing about crystals or gems?",
  "What's something you discovered about love?",
  "What's a detail about today you want to remember?",
  "What's the most interesting thing about snowflakes?",
  "What's a question you'd ask your future self?",
  "What's something about your partner that you find endlessly interesting?",
  "What's the most interesting thing about fossils?",
  "What's a moment of unexpected beauty you experienced?",
  "What's something you realized recently about yourself?",
  "What's the most interesting thing about tides?",
  "What's a dream you'd love to share with your partner?",
  "What's something that reminds you of home?",
  "What's the most interesting thing about caves?",
  "What's a small victory you had today?",
  "What's something about human connection that amazes you?",
  "What's the most interesting thing about volcanoes?",
  "What's a promise you've made to yourself?",
  "What's something you appreciate more as you get older?",
  "What's the most interesting thing about electricity?",
  "What's a way you'd love to celebrate your next milestone?",
  "What's something peaceful you witnessed today?",
  "What's the most interesting thing about clouds?",
  "What's something you've always wondered about your partner?",
  "What's the most interesting thing about seeds?",
  "What's a moment when you felt deeply connected?",
  "What's something you'd love to understand better?",
  "What's the most interesting thing about coral reefs?",
  "What's a truth you've come to accept?",
  "What's something about tomorrow that excites you?",
  "What's the most interesting thing about sand?",
  "What's a way you show love without words?",
  "What's something you're looking forward to?",
  "What's the most interesting thing about wind?",
  "What's a memory you'd love to preserve forever?",
  "What's something unexpected that made your day?",
  "What's the most interesting thing about stars?",
  "What's a new word you'd invent and what would it mean?",
  "What's something about your partner that feels like home?",
  "What's the most interesting thing about ice?",
  "What's a moment of clarity you had recently?",
  "What's something about the universe that humbles you?",
  "What's the most interesting thing about rivers?",
  "What's a piece of wisdom you'd pass on?",
  "What's something you hope never changes about your partner?",
  "What's the most interesting thing about mountains?",
  "What's a discovery you made about love?",
  "What's something worth slowing down for?",
  "What's the most interesting thing about autumn leaves?",
  "What's a moment you'd love to tell your grandchildren about?",
  "What's something that deserves more attention?",
  "What's the most interesting thing about lightning?",
  "What's a way you've been brave lately?",
  "What's something you find magical about your partner?",
  "What's the most interesting thing about bubbles?",
  "What's a door that recently opened for you?",
];

function hashDate(dateStr: string): number {
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    const char = dateStr.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return Math.abs(hash);
}

export function getDailyPrompt(dateStr: string): string {
  const index = hashDate(dateStr) % PROMPTS.length;
  return PROMPTS[index];
}

export function getDailyPromptAlternatives(dateStr: string, count: number = 3): string[] {
  const baseHash = hashDate(dateStr);
  const results: string[] = [];
  const usedIndices = new Set<number>();

  const primaryIndex = baseHash % PROMPTS.length;
  usedIndices.add(primaryIndex);

  for (let i = 1; results.length < count; i++) {
    const altHash = hashDate(dateStr + String(i));
    const altIndex = altHash % PROMPTS.length;
    if (!usedIndices.has(altIndex)) {
      usedIndices.add(altIndex);
      results.push(PROMPTS[altIndex]);
    }
  }

  return results;
}

export function getPromptCount(): number {
  return PROMPTS.length;
}
