export type QuestionCategory = "About Us" | "Dreams" | "Memories" | "Fun" | "Deep" | "Favorites";

export interface DailyQuestion {
  text: string;
  category: QuestionCategory;
}

const QUESTIONS: DailyQuestion[] = [
  { text: "What's something small your partner does that means the world to you?", category: "About Us" },
  { text: "If you could relive one day together, which would it be?", category: "Memories" },
  { text: "Where do you see us in five years?", category: "Dreams" },
  { text: "What's a song that makes you think of us?", category: "About Us" },
  { text: "Would you rather live in a treehouse or a houseboat?", category: "Fun" },
  { text: "What's a belief you hold that most people disagree with?", category: "Deep" },
  { text: "What's your all-time favorite meal?", category: "Favorites" },
  { text: "What's a trip you'd love us to take together?", category: "Dreams" },
  { text: "What's your earliest memory of us?", category: "Memories" },
  { text: "If we had a theme song, what would it be?", category: "Fun" },
  { text: "What quality in me do you admire most?", category: "About Us" },
  { text: "What scares you most about the future?", category: "Deep" },
  { text: "What's your comfort movie?", category: "Favorites" },
  { text: "What's a tradition you want us to start?", category: "Dreams" },
  { text: "What moment made you realize you loved me?", category: "Memories" },
  { text: "If you could have dinner with anyone, dead or alive, who?", category: "Fun" },
  { text: "What do you think makes our relationship different?", category: "About Us" },
  { text: "What's a lesson life taught you the hard way?", category: "Deep" },
  { text: "What's your favorite season and why?", category: "Favorites" },
  { text: "If money wasn't an issue, what would you do every day?", category: "Dreams" },
  { text: "What's the funniest thing that's happened to us?", category: "Memories" },
  { text: "Would you rather always be slightly too hot or slightly too cold?", category: "Fun" },
  { text: "What's something you've never told me?", category: "About Us" },
  { text: "What do you think happens after we die?", category: "Deep" },
  { text: "What's your favorite smell?", category: "Favorites" },
  { text: "What skill do you wish you could master overnight?", category: "Dreams" },
  { text: "What's a moment when you felt incredibly proud of us?", category: "Memories" },
  { text: "If you were a superhero, what would your power be?", category: "Fun" },
  { text: "What's the best advice you'd give your younger self?", category: "Deep" },
  { text: "What's your favorite way to spend a Sunday?", category: "Favorites" },
  { text: "What do you think is my biggest dream?", category: "About Us" },
  { text: "What's a childhood memory that shaped who you are?", category: "Memories" },
  { text: "If you could live in any fictional world, which one?", category: "Fun" },
  { text: "What makes you feel most alive?", category: "Deep" },
  { text: "What's your favorite thing about our home?", category: "Favorites" },
  { text: "Where would you want us to live when we're old?", category: "Dreams" },
  { text: "What's the most spontaneous thing we've ever done?", category: "Memories" },
  { text: "Would you rather explore space or the deep ocean?", category: "Fun" },
  { text: "What's something you're afraid to ask me?", category: "About Us" },
  { text: "What does happiness mean to you right now?", category: "Deep" },
  { text: "What's your favorite time of day?", category: "Favorites" },
  { text: "What's a goal you want us to accomplish together?", category: "Dreams" },
  { text: "What's the best gift you've ever received from me?", category: "Memories" },
  { text: "If you could instantly speak any language, which one?", category: "Fun" },
  { text: "How do you most like to receive love?", category: "About Us" },
  { text: "What would you change about the world if you could?", category: "Deep" },
  { text: "What's your favorite thing to cook or eat together?", category: "Favorites" },
  { text: "What adventure are you most looking forward to?", category: "Dreams" },
  { text: "What's a moment you wish you could freeze in time?", category: "Memories" },
  { text: "If you could swap lives with anyone for a day, who?", category: "Fun" },
  { text: "What do you think I need more of in my life?", category: "About Us" },
  { text: "What truth are you still trying to accept?", category: "Deep" },
  { text: "What's your favorite sound in the world?", category: "Favorites" },
  { text: "What kind of old couple do you want us to be?", category: "Dreams" },
  { text: "What's a tough moment that made us stronger?", category: "Memories" },
  { text: "Would you rather have unlimited books or unlimited music?", category: "Fun" },
  { text: "What's something I do that always makes you smile?", category: "About Us" },
  { text: "What are you most grateful for right now?", category: "Deep" },
  { text: "What's your favorite weather?", category: "Favorites" },
  { text: "What's something new you'd like us to try?", category: "Dreams" },
  { text: "What's our most underrated memory together?", category: "Memories" },
  { text: "If you could time travel, when would you go?", category: "Fun" },
  { text: "What do you think is my love language?", category: "About Us" },
  { text: "What's a fear you've overcome?", category: "Deep" },
  { text: "What's your favorite texture?", category: "Favorites" },
  { text: "If we could build anything together, what would it be?", category: "Dreams" },
  { text: "What's the most romantic thing that's happened to us?", category: "Memories" },
  { text: "Would you rather be able to fly or be invisible?", category: "Fun" },
  { text: "When do you feel most connected to me?", category: "About Us" },
  { text: "What's a question you're afraid to know the answer to?", category: "Deep" },
  { text: "What's your favorite place we've been together?", category: "Favorites" },
  { text: "What do you want to be remembered for?", category: "Dreams" },
  { text: "What's a little moment together you'll never forget?", category: "Memories" },
  { text: "If you could have any animal as a pet, what would it be?", category: "Fun" },
  { text: "What's something you wish I understood better about you?", category: "About Us" },
  { text: "What does love mean to you?", category: "Deep" },
  { text: "What's your favorite thing about yourself?", category: "Favorites" },
  { text: "What's a crazy dream you secretly have?", category: "Dreams" },
  { text: "What was our biggest turning point as a couple?", category: "Memories" },
  { text: "If you won the lottery tomorrow, what's the first thing you'd do?", category: "Fun" },
  { text: "What makes you feel safe with me?", category: "About Us" },
  { text: "What's a value you'll never compromise on?", category: "Deep" },
  { text: "What's your favorite comfort food?", category: "Favorites" },
  { text: "What does your ideal ordinary day look like?", category: "Dreams" },
  { text: "What's a misunderstanding we had that seems funny now?", category: "Memories" },
  { text: "Would you rather always know the truth or always be happy?", category: "Fun" },
  { text: "What's a way I've changed you for the better?", category: "About Us" },
  { text: "If you could ask the universe one question, what would it be?", category: "Deep" },
  { text: "What's your favorite thing about this time of year?", category: "Favorites" },
  { text: "What's a project you'd love us to work on together?", category: "Dreams" },
  { text: "What's the bravest thing you've seen me do?", category: "Memories" },
  { text: "If you could master any instrument overnight, which one?", category: "Fun" },
  { text: "What's one thing you never want to change about us?", category: "About Us" },
  { text: "What does success look like to you?", category: "Deep" },
  { text: "What's your favorite view?", category: "Favorites" },
  { text: "Where do you want to travel next?", category: "Dreams" },
  { text: "What's the hardest laugh you've ever had with me?", category: "Memories" },
  { text: "If you could live in any decade, which one?", category: "Fun" },
  { text: "What's the most important thing in a relationship?", category: "About Us" },
  { text: "What's something you pretend to understand but don't?", category: "Deep" },
  { text: "What's your favorite color and has it changed over time?", category: "Favorites" },
  { text: "What do you hope we never stop doing?", category: "About Us" },
  { text: "What's the weirdest thing you find attractive about me?", category: "Fun" },
  { text: "What's a moment when you felt truly understood by me?", category: "Memories" },
  { text: "What's a habit you want to build together?", category: "Dreams" },
  { text: "What do you think people misunderstand about us?", category: "About Us" },
  { text: "What keeps you up at night?", category: "Deep" },
  { text: "What's your favorite holiday?", category: "Favorites" },
  { text: "What would you name our future pet?", category: "Fun" },
  { text: "What's a promise you want to make to each other?", category: "Dreams" },
  { text: "What's the most surprising thing you've learned about me?", category: "Memories" },
  { text: "Would you rather cook together or order in?", category: "Fun" },
  { text: "How do you know when I'm having a bad day?", category: "About Us" },
  { text: "What does home mean to you?", category: "Deep" },
  { text: "What's your favorite thing about mornings?", category: "Favorites" },
  { text: "What's a fear you hope to face together?", category: "Dreams" },
  { text: "What's the best date we've ever had?", category: "Memories" },
  { text: "If you could have a conversation with your future self, what would you ask?", category: "Deep" },
  { text: "What's your go-to karaoke song?", category: "Fun" },
  { text: "What's a boundary that's made us stronger?", category: "About Us" },
  { text: "What are you most curious about?", category: "Deep" },
  { text: "What's your favorite thing I've ever cooked?", category: "Favorites" },
  { text: "What adventure would scare you but you'd try anyway?", category: "Dreams" },
  { text: "What's a small tradition we have that you love?", category: "Memories" },
  { text: "Would you rather have more time or more money?", category: "Fun" },
  { text: "What makes you proud to be with me?", category: "About Us" },
  { text: "What's the meaning of life, in your words?", category: "Deep" },
  { text: "What's your favorite thing about nighttime?", category: "Favorites" },
  { text: "What do you dream about most often?", category: "Dreams" },
  { text: "What's the first thing you noticed about me?", category: "Memories" },
  { text: "If we could only eat one cuisine forever, what would it be?", category: "Fun" },
  { text: "What's something you admire about how we handle conflict?", category: "About Us" },
  { text: "What's a belief you've changed your mind about?", category: "Deep" },
  { text: "What's your favorite book or movie and why?", category: "Favorites" },
  { text: "What's a wild thing on your bucket list?", category: "Dreams" },
  { text: "What's a time I made you feel really special?", category: "Memories" },
  { text: "Would you rather live without music or without movies?", category: "Fun" },
  { text: "What's the hardest thing about loving someone?", category: "Deep" },
  { text: "What's your favorite way to relax together?", category: "Favorites" },
  { text: "What do you think is the secret to lasting love?", category: "About Us" },
  { text: "What's the most beautiful thing you've ever seen?", category: "Memories" },
  { text: "If you could redesign our daily routine, what would it look like?", category: "Dreams" },
  { text: "Would you rather always say what you think or never speak again?", category: "Fun" },
  { text: "What makes a good day for you?", category: "Favorites" },
  { text: "What's something you've forgiven but not forgotten?", category: "Deep" },
  { text: "What nickname would you give our relationship?", category: "About Us" },
  { text: "What's a place that holds a special meaning for us?", category: "Memories" },
  { text: "If you could give us any superpower as a couple, what would it be?", category: "Fun" },
  { text: "What's one thing you wish you did more often?", category: "Dreams" },
  { text: "What's your guilty pleasure?", category: "Favorites" },
  { text: "What's the wisest thing you've ever heard?", category: "Deep" },
  { text: "What's the most comforting thing about coming home to each other?", category: "About Us" },
  { text: "What's an inside joke only we understand?", category: "Memories" },
  { text: "Would you rather always be early or always be fashionably late?", category: "Fun" },
  { text: "What brings you peace?", category: "Deep" },
  { text: "What's your favorite thing about weekends?", category: "Favorites" },
  { text: "What's a conversation we should have but haven't yet?", category: "About Us" },
  { text: "What's a moment together that felt like a movie scene?", category: "Memories" },
  { text: "If our love story was a book, what would the title be?", category: "Fun" },
  { text: "What do you hope never changes about me?", category: "About Us" },
  { text: "What's a hard truth you've come to accept?", category: "Deep" },
  { text: "What's your favorite way to show love?", category: "Favorites" },
  { text: "Where do you feel most yourself?", category: "Dreams" },
  { text: "What's the most unexpected thing about being with me?", category: "Memories" },
];

function hashDate(dateStr: string): number {
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    const char = dateStr.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return Math.abs(hash);
}

export function getDailyQuestion(dateStr: string): DailyQuestion {
  const index = hashDate(dateStr + "q") % QUESTIONS.length;
  return QUESTIONS[index];
}
