export type QuestionCategory =
  | "Us"
  | "Deep"
  | "Memory Lane"
  | "Dream Big"
  | "Hot Takes"
  | "Hypothetical"
  | "Intimacy"
  | "Gratitude"
  | "Play"
  | "Before Us";

export const QUESTION_CATEGORIES: QuestionCategory[] = [
  "Us", "Deep", "Memory Lane", "Dream Big", "Hot Takes",
  "Hypothetical", "Intimacy", "Gratitude", "Play", "Before Us"
];

export interface DailyQuestion {
  text: string;
  category: QuestionCategory;
}

const QUESTIONS: DailyQuestion[] = [
  // ── Us ──
  { text: "What's one thing I do that instantly makes your day better?", category: "Us" },
  { text: "When did you first realize this was more than a crush?", category: "Us" },
  { text: "What do you think is the thing that keeps us together?", category: "Us" },
  { text: "What's a habit of mine you secretly find adorable?", category: "Us" },
  { text: "What's something we do better as a team than anyone else?", category: "Us" },
  { text: "What's one thing about us you'd never want to change?", category: "Us" },
  { text: "What's a fight we had that actually made us stronger?", category: "Us" },
  { text: "What unspoken rule do we have that nobody else would understand?", category: "Us" },
  { text: "What do you think people notice first about us as a couple?", category: "Us" },
  { text: "What's your favorite way we say 'I love you' without saying it?", category: "Us" },
  { text: "What's a challenge we haven't faced yet that you're nervous about?", category: "Us" },
  { text: "When do you feel most like a team with me?", category: "Us" },
  { text: "What's the most 'us' thing we could possibly do on a random Tuesday?", category: "Us" },
  { text: "What's one thing you still wonder about me but have never asked?", category: "Us" },
  { text: "What song plays in your head when you think of us?", category: "Us" },
  { text: "What's the bravest thing you've ever done for this relationship?", category: "Us" },
  { text: "What do you think our biggest growth area is right now?", category: "Us" },
  { text: "How has loving me changed the way you see yourself?", category: "Us" },
  { text: "What part of our daily routine is secretly sacred to you?", category: "Us" },
  { text: "If you could freeze one moment of us in time forever, which one?", category: "Us" },
  { text: "What do you think I understand about you better than anyone?", category: "Us" },
  { text: "What's one promise you silently made to me that I don't know about?", category: "Us" },
  { text: "If you had to describe the feeling of being with me to a blind person, how would you?", category: "Us" },
  { text: "What part of me did you fall in love with last?", category: "Us" },
  { text: "What's the hardest sacrifice you've made for us that I might not know about?", category: "Us" },
  { text: "If our love had a scent, what would it smell like?", category: "Us" },
  { text: "What do you think we argue about that's actually about something deeper?", category: "Us" },
  { text: "When's the last time you chose us over something you really wanted?", category: "Us" },
  { text: "What part of your identity shifted when we became 'us'?", category: "Us" },
  { text: "What's a truth about our relationship that took you a long time to see?", category: "Us" },

  // ── Deep ──
  { text: "What's a belief you hold that most people in your life would disagree with?", category: "Deep" },
  { text: "What's the hardest truth you've had to accept about yourself?", category: "Deep" },
  { text: "If you could know the absolute truth to one question, what would you ask?", category: "Deep" },
  { text: "What does 'home' mean to you — not a place, a feeling?", category: "Deep" },
  { text: "What are you most afraid of losing?", category: "Deep" },
  { text: "Do you think people can truly change, or just learn to manage who they are?", category: "Deep" },
  { text: "What's something you pretend doesn't bother you but actually does?", category: "Deep" },
  { text: "What would you do differently if nobody was watching or judging?", category: "Deep" },
  { text: "Do you think we choose who we love, or does it choose us?", category: "Deep" },
  { text: "What's something you've forgiven but never forgotten?", category: "Deep" },
  { text: "What does success actually look like to you — not what society says?", category: "Deep" },
  { text: "What's a value you'll never compromise on, no matter what?", category: "Deep" },
  { text: "What keeps you up at 3am?", category: "Deep" },
  { text: "What lesson did life teach you in the worst possible way?", category: "Deep" },
  { text: "What are you running from? What are you running toward?", category: "Deep" },
  { text: "What does vulnerability feel like in your body?", category: "Deep" },
  { text: "What's one thing you're still trying to prove to yourself?", category: "Deep" },
  { text: "What emotion do you have the hardest time sitting with?", category: "Deep" },
  { text: "What do you think your purpose is — or are you still figuring it out?", category: "Deep" },
  { text: "What's one thing about the world that breaks your heart?", category: "Deep" },
  { text: "What's a part of your personality you perform vs. one that's truly you?", category: "Deep" },
  { text: "What would you do with your life if you knew no one would ever judge you?", category: "Deep" },
  { text: "What's a feeling you've never been able to put into words?", category: "Deep" },
  { text: "What have you outgrown that you haven't let go of yet?", category: "Deep" },
  { text: "If you could sit with your pain instead of running from it, what would it tell you?", category: "Deep" },
  { text: "What lie did you believe about yourself for too long?", category: "Deep" },
  { text: "What would you want to be remembered for if no one knew your name?", category: "Deep" },
  { text: "What's the loneliest you've ever felt, even around people?", category: "Deep" },
  { text: "What's a door you closed that still calls to you sometimes?", category: "Deep" },
  { text: "If your anxiety had a voice, what does it say on repeat?", category: "Deep" },

  // ── Memory Lane ──
  { text: "What's the first thing you remember thinking when we met?", category: "Memory Lane" },
  { text: "What's a random moment together that you think about more than you should?", category: "Memory Lane" },
  { text: "What's a moment where you fell in love with me all over again?", category: "Memory Lane" },
  { text: "What's the hardest laugh we've ever shared?", category: "Memory Lane" },
  { text: "What's a trip or adventure we took that changed something between us?", category: "Memory Lane" },
  { text: "What's a gift I gave you that meant more than I probably realized?", category: "Memory Lane" },
  { text: "What's a photo of us you wish existed but we never took?", category: "Memory Lane" },
  { text: "What's an inside joke between us that still makes you smile?", category: "Memory Lane" },
  { text: "What's the most spontaneous thing we've ever done?", category: "Memory Lane" },
  { text: "What's a meal we shared that you'll never forget?", category: "Memory Lane" },
  { text: "What's your favorite 'normal' memory of us — not a big event, just ordinary life?", category: "Memory Lane" },
  { text: "What's the most romantic thing that's happened between us naturally?", category: "Memory Lane" },
  { text: "What place holds the most memories for us?", category: "Memory Lane" },
  { text: "What's a time I made you feel completely safe?", category: "Memory Lane" },
  { text: "What moment together felt like a scene from a movie?", category: "Memory Lane" },
  { text: "What's a small kindness from me that you've never forgotten?", category: "Memory Lane" },
  { text: "What was the turning point when 'dating' became 'this is it'?", category: "Memory Lane" },
  { text: "What's a quiet moment between us that hit you harder than it should have?", category: "Memory Lane" },
  { text: "What's something I said in passing that you never forgot?", category: "Memory Lane" },
  { text: "Describe the exact moment you knew you trusted me.", category: "Memory Lane" },
  { text: "What's a time we were completely lost — literally or figuratively — and it brought us closer?", category: "Memory Lane" },
  { text: "What smell or sound instantly transports you back to an early memory of us?", category: "Memory Lane" },
  { text: "What's a version of me you miss — not because I changed for the worse, just because time moved?", category: "Memory Lane" },
  { text: "What's the most honest conversation we've ever had?", category: "Memory Lane" },
  { text: "What's a night together you'd relive if you could — not to change, just to feel again?", category: "Memory Lane" },

  // ── Dream Big ──
  { text: "If money and time were no object, what would our life look like in 10 years?", category: "Dream Big" },
  { text: "What's one wild dream you haven't told anyone about?", category: "Dream Big" },
  { text: "Where in the world would you build our dream home?", category: "Dream Big" },
  { text: "What's a skill you'd love both of us to learn together?", category: "Dream Big" },
  { text: "If we could start a business together, what would it be?", category: "Dream Big" },
  { text: "What kind of old couple do you want us to be?", category: "Dream Big" },
  { text: "If we could take a year off and go anywhere, what's the itinerary?", category: "Dream Big" },
  { text: "What's a project you'd love us to build or create together?", category: "Dream Big" },
  { text: "What's a tradition you want us to start this year?", category: "Dream Big" },
  { text: "What does your ideal regular day look like in 5 years?", category: "Dream Big" },
  { text: "If we could live abroad for a year, where would we go?", category: "Dream Big" },
  { text: "What's a fear you want to face together?", category: "Dream Big" },
  { text: "What's the craziest goal you'd pursue if failure wasn't an option?", category: "Dream Big" },
  { text: "How do you want people to describe our life when we're 80?", category: "Dream Big" },
  { text: "What experience do you want to have at least once in your life?", category: "Dream Big" },
  { text: "What does 'legacy' mean to you?", category: "Dream Big" },
  { text: "What's the next adventure you want us to take?", category: "Dream Big" },
  { text: "What's a promise you want us to make to each other right now?", category: "Dream Big" },
  { text: "If you could design one perfect day for us five years from now, what does it look like?", category: "Dream Big" },
  { text: "What's something you want to build — not buy — with your own hands someday?", category: "Dream Big" },
  { text: "If we dropped everything and started over in a new city tomorrow, where and why?", category: "Dream Big" },
  { text: "What's a conversation we need to have about our future that we keep postponing?", category: "Dream Big" },
  { text: "What would you attempt if you knew I'd support you no matter what?", category: "Dream Big" },
  { text: "What does 'enough' look like — enough money, enough career, enough stuff?", category: "Dream Big" },
  { text: "What's one thing you want our future kids — or future selves — to say about how we lived?", category: "Dream Big" },

  // ── Hot Takes ──
  { text: "What's a popular opinion that you think is completely wrong?", category: "Hot Takes" },
  { text: "Do you think social media helps or hurts relationships?", category: "Hot Takes" },
  { text: "Is it ever okay to lie to protect someone's feelings?", category: "Hot Takes" },
  { text: "What's a 'red flag' that you actually think is fine?", category: "Hot Takes" },
  { text: "Do you think couples should share passwords?", category: "Hot Takes" },
  { text: "Is being 'too comfortable' in a relationship a real thing?", category: "Hot Takes" },
  { text: "Do you think people should stay friends with their exes?", category: "Hot Takes" },
  { text: "What's the worst relationship advice people give?", category: "Hot Takes" },
  { text: "Is jealousy always bad, or can it be healthy sometimes?", category: "Hot Takes" },
  { text: "What's something society romanticizes that's actually toxic?", category: "Hot Takes" },
  { text: "What's a hill you'd die on that nobody else cares about?", category: "Hot Takes" },
  { text: "Is 'the one' real, or do you just choose someone and build?", category: "Hot Takes" },
  { text: "Do you think people fall out of love, or just stop choosing each other?", category: "Hot Takes" },
  { text: "Is it better to be brutally honest or gently kind?", category: "Hot Takes" },
  { text: "What's the biggest myth about long-term relationships?", category: "Hot Takes" },
  { text: "Should your partner be your best friend, or is that too much pressure?", category: "Hot Takes" },
  { text: "Is 'never go to bed angry' good advice or terrible advice?", category: "Hot Takes" },
  { text: "Do you think couples therapy should be normal, not a last resort?", category: "Hot Takes" },
  { text: "Is keeping a secret the same as lying?", category: "Hot Takes" },
  { text: "What's something most people find romantic that actually creeps you out?", category: "Hot Takes" },
  { text: "Do you think people settle — and is that always a bad thing?", category: "Hot Takes" },
  { text: "Is independence in a relationship overrated or underrated?", category: "Hot Takes" },
  { text: "Can you truly forgive someone who never apologizes?", category: "Hot Takes" },
  { text: "What's a relationship rule most couples follow that you think is stupid?", category: "Hot Takes" },
  { text: "Is love a feeling, a decision, or something else entirely?", category: "Hot Takes" },

  // ── Hypothetical ──
  { text: "If you could wake up tomorrow with one new ability, what would it be?", category: "Hypothetical" },
  { text: "If we had to survive a zombie apocalypse together, what's our game plan?", category: "Hypothetical" },
  { text: "If you could live in any fictional universe, which one and why?", category: "Hypothetical" },
  { text: "Would you rather always know what people are thinking or always know the future?", category: "Hypothetical" },
  { text: "If you could have dinner with anyone — alive or dead — who would it be?", category: "Hypothetical" },
  { text: "Would you rather be famous and lonely or unknown and deeply loved?", category: "Hypothetical" },
  { text: "If you could swap lives with me for 24 hours, what's the first thing you'd do?", category: "Hypothetical" },
  { text: "If we found a suitcase with $1 million cash, what do we do?", category: "Hypothetical" },
  { text: "Would you rather never age physically or never age mentally?", category: "Hypothetical" },
  { text: "If aliens landed and asked you to explain love, what would you say?", category: "Hypothetical" },
  { text: "Would you rather have more time or more money?", category: "Hypothetical" },
  { text: "If you could uninvent one thing, what would it be?", category: "Hypothetical" },
  { text: "Would you rather live in a cabin in the mountains or a beach house by the ocean?", category: "Hypothetical" },
  { text: "If you could relive any year of your life, which would it be?", category: "Hypothetical" },
  { text: "If you could make one rule everyone in the world had to follow, what would it be?", category: "Hypothetical" },
  { text: "Would you rather live without music or live without movies?", category: "Hypothetical" },
  { text: "If we could teleport anywhere right now for one hour, where do we go?", category: "Hypothetical" },
  { text: "If you could only save five memories from your entire life, which five?", category: "Hypothetical" },
  { text: "If you woke up and the last five years had been a dream, what would you do first?", category: "Hypothetical" },
  { text: "If you could live one day with no consequences — nothing you do carries over — what do you do?", category: "Hypothetical" },
  { text: "If a genie said 'I'll grant one wish but you can never tell anyone,' what do you wish for?", category: "Hypothetical" },
  { text: "If we could read each other's thoughts for 10 minutes, would you want to?", category: "Hypothetical" },
  { text: "If you could remove one emotion permanently, would you — and which one?", category: "Hypothetical" },
  { text: "If you had to write a letter to open 20 years from now, what would it say?", category: "Hypothetical" },
  { text: "If you could ask your future self one thing, what would it be?", category: "Hypothetical" },

  // ── Intimacy ──
  { text: "What's one thing I could do to make you feel more loved this week?", category: "Intimacy" },
  { text: "When do you feel closest to me?", category: "Intimacy" },
  { text: "What's something vulnerable you've been wanting to share but haven't?", category: "Intimacy" },
  { text: "How do you most like to be comforted when you're upset?", category: "Intimacy" },
  { text: "What does feeling safe in our relationship mean to you?", category: "Intimacy" },
  { text: "What's your love language when you're stressed vs. when you're happy?", category: "Intimacy" },
  { text: "What's a way I show love that maybe I don't even realize?", category: "Intimacy" },
  { text: "When was the last time you felt truly seen by me?", category: "Intimacy" },
  { text: "What's one thing you need from me that you've been too shy to ask for?", category: "Intimacy" },
  { text: "What does trust look like to you in a relationship?", category: "Intimacy" },
  { text: "What's the most attractive thing about me that isn't physical?", category: "Intimacy" },
  { text: "What's the hardest thing about being emotionally open with me?", category: "Intimacy" },
  { text: "What does intimacy mean to you beyond the physical?", category: "Intimacy" },
  { text: "What's a part of yourself you're still learning to love?", category: "Intimacy" },
  { text: "What do you wish you could tell me without worrying how I'd react?", category: "Intimacy" },
  { text: "How can I be a better listener for you?", category: "Intimacy" },
  { text: "What scares you most about being fully known by someone?", category: "Intimacy" },
  { text: "What's the most tender moment we've shared?", category: "Intimacy" },
  { text: "When do you feel the most 'you' around me?", category: "Intimacy" },
  { text: "What do you need more of in our relationship right now?", category: "Intimacy" },
  { text: "What part of your body do you wish I paid more attention to — not sexually, just tenderly?", category: "Intimacy" },
  { text: "What's a way I could hold space for you better when you're shutting down?", category: "Intimacy" },
  { text: "When do you feel most desired by me — and when do you wish you did?", category: "Intimacy" },
  { text: "What's something you hide from me not because you don't trust me, but because you don't trust yourself to say it right?", category: "Intimacy" },
  { text: "What does it feel like when we're really connected vs. when we're just going through the motions?", category: "Intimacy" },

  // ── Gratitude ──
  { text: "What's something I did recently that made you feel appreciated?", category: "Gratitude" },
  { text: "What's one thing about your life right now that you'd never trade?", category: "Gratitude" },
  { text: "What's a quality in me that you're most grateful for?", category: "Gratitude" },
  { text: "What's the best thing that happened to you this week?", category: "Gratitude" },
  { text: "What's a 'boring' part of our routine that you secretly love?", category: "Gratitude" },
  { text: "What's one thing about today that you want to remember?", category: "Gratitude" },
  { text: "What's a lesson from a hard time that you're now grateful for?", category: "Gratitude" },
  { text: "What's the most underrated thing about our life together?", category: "Gratitude" },
  { text: "What's a simple pleasure that always makes your day?", category: "Gratitude" },
  { text: "When was the last time you felt genuinely lucky?", category: "Gratitude" },
  { text: "What's one way I've made your life easier that I probably don't know about?", category: "Gratitude" },
  { text: "What are three small things you're grateful for right now?", category: "Gratitude" },
  { text: "What's something about this season of life that you want to savor?", category: "Gratitude" },
  { text: "What's a comfort you have now that you once only dreamed about?", category: "Gratitude" },
  { text: "What about me surprised you in the best way?", category: "Gratitude" },
  { text: "What's one way our relationship has made you a better person?", category: "Gratitude" },
  { text: "What's something you used to take for granted but don't anymore?", category: "Gratitude" },
  { text: "What's the best risk you've ever taken?", category: "Gratitude" },
  { text: "What's one thing about our home that makes you feel at peace?", category: "Gratitude" },
  { text: "What's a kindness someone showed you this week that you didn't expect?", category: "Gratitude" },
  { text: "What's something about me that you're grateful you didn't notice at first — it revealed itself slowly?", category: "Gratitude" },
  { text: "What ordinary moment this week felt secretly extraordinary?", category: "Gratitude" },
  { text: "What's a struggle we went through that you're now oddly thankful for?", category: "Gratitude" },
  { text: "What's one thing about your body that you've made peace with?", category: "Gratitude" },
  { text: "If you could bottle one feeling from this week and keep it forever, what would it be?", category: "Gratitude" },

  // ── Play ──
  { text: "What's the most embarrassing song on your playlist right now?", category: "Play" },
  { text: "If you were a sandwich, what kind of sandwich would you be?", category: "Play" },
  { text: "What's the worst fashion choice you've ever made?", category: "Play" },
  { text: "If our pets could talk, what would they say about us?", category: "Play" },
  { text: "What's the dumbest thing you've ever Googled?", category: "Play" },
  { text: "What's your guilty pleasure TV show or movie?", category: "Play" },
  { text: "If you could only use one emoji for the rest of your life, which one?", category: "Play" },
  { text: "What's the most useless talent you have?", category: "Play" },
  { text: "What's your go-to karaoke song, no hesitation?", category: "Play" },
  { text: "What nickname would you secretly love me to call you?", category: "Play" },
  { text: "If we had a couples Halloween costume, what would it be?", category: "Play" },
  { text: "What's the weirdest food combo you genuinely enjoy?", category: "Play" },
  { text: "If we started a band, what would we be called?", category: "Play" },
  { text: "What celebrity do people say you look like (and do you agree)?", category: "Play" },
  { text: "What's your most controversial food take?", category: "Play" },
  { text: "If we had to compete on a reality show, which one would we dominate?", category: "Play" },
  { text: "What would your rapper name be?", category: "Play" },
  { text: "If our relationship had a Yelp review, what would it say?", category: "Play" },
  { text: "What's the most unhinged thing you've done when you were home alone?", category: "Play" },
  { text: "If you could only watch one movie for the rest of your life, what is it — and don't think too hard?", category: "Play" },
  { text: "What's the pettiest thing you've ever been right about?", category: "Play" },
  { text: "Describe me using only food items.", category: "Play" },
  { text: "What's a word you've been mispronouncing your entire life?", category: "Play" },
  { text: "If we had a joint TikTok, what would our niche be?", category: "Play" },
  { text: "What's the most absurd hill you'd die on at a dinner party?", category: "Play" },

  // ── Before Us ──
  { text: "What were you like as a kid? Describe yourself in three words.", category: "Before Us" },
  { text: "What's a childhood memory that you think about a lot?", category: "Before Us" },
  { text: "What was your family's dinner table like growing up?", category: "Before Us" },
  { text: "Who was your first crush and what were they like?", category: "Before Us" },
  { text: "What's a phase you went through that you'd love to forget?", category: "Before Us" },
  { text: "What's the best thing your parents taught you about love?", category: "Before Us" },
  { text: "What's a dream you had as a kid that you've let go of?", category: "Before Us" },
  { text: "What was the hardest year of your life before we met?", category: "Before Us" },
  { text: "What's a school memory — good or bad — that shaped you?", category: "Before Us" },
  { text: "Who was the most influential person in your childhood?", category: "Before Us" },
  { text: "What did you want to be when you grew up?", category: "Before Us" },
  { text: "What's the biggest lesson a past relationship taught you?", category: "Before Us" },
  { text: "What's a place from your childhood that you'd love to visit again?", category: "Before Us" },
  { text: "What were you most insecure about as a teenager?", category: "Before Us" },
  { text: "What's a tradition from your family that you want to keep alive?", category: "Before Us" },
  { text: "What was the first job you ever had?", category: "Before Us" },
  { text: "What's something about your hometown that you miss?", category: "Before Us" },
  { text: "Who was your childhood best friend and where are they now?", category: "Before Us" },
  { text: "What's a moment from before we met that you wish I could've seen?", category: "Before Us" },
  { text: "If you could go back and tell your 16-year-old self one thing, what would it be?", category: "Before Us" },
  { text: "What's a version of yourself from before we met that you miss sometimes?", category: "Before Us" },
  { text: "What was your relationship with loneliness like before me?", category: "Before Us" },
  { text: "What's a scar — physical or emotional — that has a story I haven't heard?", category: "Before Us" },
  { text: "What's the worst advice your family gave you about relationships?", category: "Before Us" },
  { text: "What did love look like in your house growing up — and how did that shape what you want now?", category: "Before Us" },
];

function hashDate(dateStr: string): number {
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    const char = dateStr.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return Math.abs(hash);
}

export function getDailyQuestion(dateStr: string): DailyQuestion {
  const index = hashDate(dateStr + "q") % QUESTIONS.length;
  return QUESTIONS[index];
}
